window.mockData = {
  cooperatives: [
    { id: "coop-1", name: "Chennai Skilled Workers Cooperative", location: "Chennai", members: 340, founded: 2018 },
    { id: "coop-2", name: "Delhi Household & Labor Union", location: "Delhi", members: 520, founded: 2015 },
    { id: "coop-3", name: "Mumbai Community & Caregivers Society", location: "Mumbai", members: 280, founded: 2020 },
    { id: "coop-4", name: "Bangalore Technicians Cooperative Board", location: "Bangalore", members: 410, founded: 2017 }
  ],
  services: [
    { id: "plumbing", translationKey: "plumbing", baseRate: 250, hourlyRate: 150, icon: "plumbing", status: "Enabled" },
    { id: "electrical", translationKey: "electrical", baseRate: 300, hourlyRate: 200, icon: "electrical", status: "Enabled" },
    { id: "carpentry", translationKey: "carpentry", baseRate: 280, hourlyRate: 180, icon: "carpentry", status: "Enabled" },
    { id: "painting", translationKey: "painting", baseRate: 350, hourlyRate: 220, icon: "painting", status: "Enabled" },
    { id: "caregiving", translationKey: "caregiving", baseRate: 400, hourlyRate: 250, icon: "caregiving", status: "Enabled" },
    { id: "gardening", translationKey: "gardening", baseRate: 200, hourlyRate: 120, icon: "gardening", status: "Enabled" },
    { id: "cleaning", translationKey: "cleaning", baseRate: 180, hourlyRate: 100, icon: "cleaning", status: "Enabled" },
    { id: "domesticHelp", translationKey: "domesticHelp", baseRate: 220, hourlyRate: 130, icon: "domesticHelp", status: "Enabled" }
  ],
  topWorkers: [
    {
      id: "worker-1",
      name: "Ravi Kumar",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150",
      skill: "plumbing",
      serviceCategory: "plumbing",
      rating: 4.8,
      distance: 1.2,
      experience: 6,
      location: "Adyar, Chennai",
      availability: "Available",
      availabilityStatus: "Available",
      status: "Waiting",
      currentStatus: "Waiting",
      cooperative: "Chennai Skilled Workers Cooperative",
      ranking: 1,
      phone: "+91 98765 43210"
    },
    {
      id: "worker-2",
      name: "Priya Shanmugam",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150",
      skill: "plumbing",
      serviceCategory: "plumbing",
      rating: 4.9,
      distance: 1.8,
      experience: 5,
      location: "Mylapore, Chennai",
      availability: "Available",
      availabilityStatus: "Available",
      status: "Waiting",
      currentStatus: "Waiting",
      cooperative: "Chennai Skilled Workers Cooperative",
      ranking: 2,
      phone: "+91 87654 32109"
    },
    {
      id: "worker-3",
      name: "Amit Singh",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150",
      skill: "plumbing",
      serviceCategory: "plumbing",
      rating: 4.7,
      distance: 2.5,
      experience: 8,
      location: "Connaught Place, New Delhi",
      availability: "Available",
      availabilityStatus: "Available",
      status: "Waiting",
      currentStatus: "Waiting",
      cooperative: "Delhi Household & Labor Union",
      ranking: 3,
      phone: "+91 76543 21098"
    }
  ],
  widerPool: [
    {
      id: "worker-4",
      name: "Vikram Rathore",
      avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150",
      skill: "plumbing",
      serviceCategory: "plumbing",
      rating: 4.5,
      distance: 3.4,
      experience: 4,
      location: "Andheri, Mumbai",
      availability: "Available",
      availabilityStatus: "Available",
      status: "Waiting",
      currentStatus: "Waiting",
      cooperative: "Mumbai Community & Caregivers Society",
      ranking: 4,
      phone: "+91 95432 10987"
    },
    {
      id: "worker-5",
      name: "Suresh Babu",
      avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150",
      skill: "plumbing",
      serviceCategory: "plumbing",
      rating: 4.2,
      distance: 4.1,
      experience: 10,
      location: "T. Nagar, Chennai",
      availability: "Available",
      availabilityStatus: "Available",
      status: "Waiting",
      currentStatus: "Waiting",
      cooperative: "Chennai Skilled Workers Cooperative",
      ranking: 5,
      phone: "+91 94321 09876"
    },
    {
      id: "worker-6",
      name: "Lakshmi Narayanan",
      avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150",
      skill: "plumbing",
      serviceCategory: "plumbing",
      rating: 4.6,
      distance: 4.8,
      experience: 7,
      location: "Indiranagar, Bangalore",
      availability: "Available",
      availabilityStatus: "Available",
      status: "Waiting",
      currentStatus: "Waiting",
      cooperative: "Bangalore Technicians Cooperative Board",
      ranking: 6,
      phone: "+91 93210 98765"
    },
    // Other skills for worker dashboard simulation
    {
      id: "worker-7",
      name: "Rajesh Kannan",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150",
      skill: "electrical",
      serviceCategory: "electrical",
      rating: 4.9,
      distance: 1.5,
      experience: 9,
      location: "Velachery, Chennai",
      availability: "Available",
      availabilityStatus: "Available",
      status: "Available",
      currentStatus: "Available",
      cooperative: "Chennai Skilled Workers Cooperative",
      ranking: 1,
      phone: "+91 92109 87654"
    },
    {
      id: "worker-8",
      name: "Meena Kumari",
      avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150",
      skill: "caregiving",
      serviceCategory: "caregiving",
      rating: 4.8,
      distance: 2.1,
      experience: 5,
      location: "Bandra, Mumbai",
      availability: "Available",
      availabilityStatus: "Available",
      status: "Available",
      currentStatus: "Available",
      cooperative: "Mumbai Community & Caregivers Society",
      ranking: 2,
      phone: "+91 91098 76543"
    }
  ],
  customers: [
    { id: "cust-1", name: "Anand Verma", email: "anand@example.com", phone: "9876543210", address: "12, Kasturba Gandhi Marg, Connaught Place, New Delhi" },
    { id: "cust-2", name: "Deepika Ramaswamy", email: "deepika@example.com", phone: "8765432109", address: "54, Gandhi Nagar Main Road, Adyar, Chennai" },
    { id: "cust-3", name: "Arun Kumar", email: "arun@example.com", phone: "9123456780", address: "24, Besant Nagar Beach Road, Chennai" }
  ],
  initialBookings: [
    {
      id: "book-100",
      customerId: "cust-3",
      customerName: "Arun Kumar",
      serviceId: "electrical",
      workerId: "worker-2",
      workerName: "Priya Shanmugam",
      workerPhone: "+91 98765 43211",
      cooperative: "Chennai Skilled Workers Cooperative",
      location: "24, Besant Nagar Beach Road, Chennai",
      description: "Ceiling fan installation and main switchboard safety check.",
      datetime: "2026-08-22T11:30",
      urgency: "Normal",
      estimatedCost: 350,
      status: "Completed",
      rating: 5,
      review: "Priya arrived on time and fixed the switchboard neatly. True cooperative professional.",
      continuityTriggered: false
    },
    {
      id: "book-101",
      customerId: "cust-2",
      customerName: "Deepika Ramaswamy",
      serviceId: "plumbing",
      workerId: "worker-1",
      workerName: "Ravi Kumar",
      workerPhone: "+91 98765 43210",
      cooperative: "Chennai Skilled Workers Cooperative",
      location: "54, Gandhi Nagar Main Road, Adyar, Chennai",
      description: "Repair bathroom shower mixer and inspect kitchen drain blockage.",
      datetime: "2026-08-20T10:00",
      urgency: "Normal",
      estimatedCost: 400,
      status: "Completed",
      rating: 5,
      review: "Excellent service! Ravi was very polite and solved the issue quickly. He had all the tools and explained the cooperative billing structure clearly.",
      continuityTriggered: false
    },
    {
      id: "book-102",
      customerId: "cust-2",
      customerName: "Deepika Ramaswamy",
      serviceId: "cleaning",
      workerId: "worker-8",
      workerName: "Meena Kumari",
      workerPhone: "+91 91098 76543",
      cooperative: "Mumbai Community & Caregivers Society",
      location: "54, Gandhi Nagar Main Road, Adyar, Chennai",
      description: "Complete post-festive cleaning of 3BHK house.",
      datetime: "2026-08-22T09:00",
      urgency: "Normal",
      estimatedCost: 1180,
      status: "Completed",
      rating: 4,
      review: "Very professional cleaners. They arrived on time. Deducting one star only because they ran out of a cleaning solution, but overall coop service was great.",
      continuityTriggered: false
    },
    {
      id: "book-103",
      customerId: "cust-1",
      customerName: "Anand Verma",
      serviceId: "plumbing",
      workerId: "worker-1",
      workerName: "Ravi Kumar",
      workerPhone: "+91 98765 43210",
      cooperative: "Chennai Skilled Workers Cooperative",
      location: "12, Kasturba Gandhi Marg, Connaught Place, New Delhi",
      description: "Install new kitchen sink faucet and fix leakage in inlet pipe.",
      datetime: "2026-08-21T14:30",
      urgency: "Normal",
      estimatedCost: 350,
      status: "Completed",
      rating: 5,
      review: "Ravi did a great job. Quick and highly professional.",
      continuityTriggered: false
    },
    {
      id: "book-104",
      customerId: "cust-2",
      customerName: "Deepika Ramaswamy",
      serviceId: "plumbing",
      workerId: "worker-1",
      workerName: "Ravi Kumar",
      workerPhone: "+91 98765 43210",
      cooperative: "Chennai Skilled Workers Cooperative",
      location: "54, Gandhi Nagar Main Road, Adyar, Chennai",
      description: "Water tank valve replacement.",
      datetime: "2026-08-22T11:00",
      urgency: "Normal",
      estimatedCost: 500,
      status: "Completed",
      rating: 4,
      review: "Arrived on time. The cooperative society rates are very transparent.",
      continuityTriggered: false
    },
    {
      id: "book-105",
      customerId: "cust-1",
      customerName: "Anand Verma",
      serviceId: "plumbing",
      workerId: "worker-1",
      workerName: "Ravi Kumar",
      workerPhone: "+91 98765 43210",
      cooperative: "Chennai Skilled Workers Cooperative",
      location: "12, Kasturba Gandhi Marg, Connaught Place, New Delhi",
      description: "Basement drainage pipeline cleaning.",
      datetime: "2026-08-23T15:00",
      urgency: "Urgent",
      estimatedCost: 650,
      status: "Completed",
      rating: 5,
      review: "Emergency response was fantastic. Highly recommended plumbing crew.",
      continuityTriggered: false
    },
    {
      id: "book-106",
      customerId: "cust-2",
      customerName: "Deepika Ramaswamy",
      serviceId: "plumbing",
      workerId: "worker-1",
      workerName: "Ravi Kumar",
      workerPhone: "+91 98765 43210",
      cooperative: "Chennai Skilled Workers Cooperative",
      location: "54, Gandhi Nagar Main Road, Adyar, Chennai",
      description: "Bathroom wash basin fitting installation.",
      datetime: "2026-08-24T10:00",
      urgency: "Normal",
      estimatedCost: 300,
      status: "Completed",
      rating: 5,
      review: "Very neat work and friendly attitude.",
      continuityTriggered: false
    },
    {
      id: "book-107",
      customerId: "cust-1",
      customerName: "Anand Verma",
      serviceId: "plumbing",
      workerId: "worker-1",
      workerName: "Ravi Kumar",
      workerPhone: "+91 98765 43210",
      cooperative: "Chennai Skilled Workers Cooperative",
      location: "12, Kasturba Gandhi Marg, Connaught Place, New Delhi",
      description: "Geyser inlet outlet hose replacement.",
      datetime: "2026-08-24T16:30",
      urgency: "Normal",
      estimatedCost: 280,
      status: "Completed",
      rating: 5,
      review: "Quick and efficient resolution.",
      continuityTriggered: false
    },
    {
      id: "book-108",
      customerId: "cust-2",
      customerName: "Deepika Ramaswamy",
      serviceId: "plumbing",
      workerId: "worker-1",
      workerName: "Ravi Kumar",
      workerPhone: "+91 98765 43210",
      cooperative: "Chennai Skilled Workers Cooperative",
      location: "54, Gandhi Nagar Main Road, Adyar, Chennai",
      description: "Kitchen water purifier line connector block.",
      datetime: "2026-08-25T09:00",
      urgency: "Normal",
      estimatedCost: 220,
      status: "Completed",
      rating: 5,
      review: "Excellent response, solved the Purifier line issue in 10 minutes.",
      continuityTriggered: false
    },
    {
      id: "book-109",
      customerId: "cust-2",
      customerName: "Deepika Ramaswamy",
      serviceId: "plumbing",
      workerId: "worker-1",
      workerName: "Ravi Kumar",
      workerPhone: "+91 98765 43210",
      cooperative: "Chennai Skilled Workers Cooperative",
      location: "54, Gandhi Nagar Main Road, Adyar, Chennai",
      description: "Outdoor sprinkler line joint leak check.",
      datetime: "2026-08-19T13:00",
      urgency: "Normal",
      estimatedCost: 200,
      status: "Cancelled",
      rating: null,
      review: null,
      continuityTriggered: false
    },
    {
      id: "book-110",
      customerId: "cust-1",
      customerName: "Arun Kumar",
      serviceId: "plumbing",
      workerId: "worker-1",
      workerName: "Ravi Kumar",
      workerPhone: "+91 98765 43210",
      cooperative: "Chennai Skilled Workers Cooperative",
      location: "Flat 4B, 3rd Avenue, Anna Nagar West, Chennai",
      description: "Kitchen pipeline valve leakage and low water pressure inspection.",
      datetime: "2026-09-15T10:30",
      urgency: "Normal",
      estimatedCost: 350,
      status: "Accepted",
      rating: null,
      review: null,
      continuityTriggered: false
    }
  ]
};
